// LastApple.Web/ClientApp/src/components/Player/PlaylistTrackGroup.tsx
import React from 'react';
import { Dropdown } from "react-bootstrap";
import { CustomToggle } from "./CustomToggle";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEllipsisH } from "@fortawesome/free-solid-svg-icons/faEllipsisH";
import musicKit from "../../musicKit";
import { faFolderPlus, faTrashAlt } from "@fortawesome/free-solid-svg-icons";

type PlaylistTrackGroupProps = {
    currentTrack: MusicKit.MediaItem,
    tracks: MusicKit.MediaItem[],
    isPlaying: boolean,
    index: number,
    onRemove(position: number, count: number),
    addAlbumToLibrary(item: MusicKit.MediaItem): void,
}

export const PlaylistTrackGroup = React.memo((props: React.PropsWithChildren<PlaylistTrackGroupProps>) =>
    <div style={{ marginBottom: '20px' }}>
        <div style={{
            background: '#00000099',
            marginBottom: '5px',
            padding: '.4rem'
        }}>
            <img style={{
                height: '60px',
                width: '60px',
                verticalAlign: 'top'
            }} alt={'album logo'} src={props.tracks?.[0]?.attributes?.artwork?.url?.replace('{w}x{h}', '60x60') || ''}/>
            <div className={'album-header'} style={{
                display: 'inline-block',
                width: 'calc(100% - 60px)',
                padding: '7px 0 0 10px'
            }}>
                <Dropdown align="end" style={{
                    float: 'right',
                    margin: '5px 0',
                    fontSize: '22px'
                }}>
                    <Dropdown.Toggle as={CustomToggle} id={`item-dropdown-group-${props.index}`}>
                        <FontAwesomeIcon style={{ verticalAlign: 'bottom', margin: '.6rem .5rem' }} icon={faEllipsisH} />
                    </Dropdown.Toggle>
                    <Dropdown.Menu>
                        <Dropdown.Item onSelect={() => props.tracks?.[0] && props.addAlbumToLibrary(props.tracks[0])} disabled={!musicKit.instance?.isAuthorized}>
                                        <span style={{
                                            display: 'inline-block',
                                            width: '16px',
                                            fontSize: '16px',
                                            marginRight: '10px'
                                        }}>
                                            <FontAwesomeIcon icon={faFolderPlus}/>
                                        </span>
                            <span>Add to your AppleMusic Library</span>
                        </Dropdown.Item>
                        <Dropdown.Item onSelect={() => props.onRemove(props.index, props.tracks.length)}>
                                        <span style={{
                                            display: 'inline-block',
                                            width: '16px',
                                            fontSize: '16px',
                                            marginRight: '10px'
                                        }}>
                                            <FontAwesomeIcon icon={faTrashAlt}/>
                                        </span>
                            <span>Delete from this station</span>
                        </Dropdown.Item>
                    </Dropdown.Menu>
                </Dropdown>
                <h5 style={{ margin: '0' }}>{props.tracks?.[0]?.attributes?.albumName || ''}</h5>
                <h6 style={{ margin: '.5rem 0 0 0', color: '#BBB' }}>{props.tracks?.[0]?.attributes?.artistName || ''}</h6>
            </div>
        </div>
        {props.children}
    </div>);

// LastApple.Web/ClientApp-Svelte/src/lib/components/Player/PlaylistTrackGroup.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import CustomToggle from './CustomToggle.svelte';
	import { getImageUrl } from '$lib/utils/imageUtils';
	import Icon from '$lib/components/Icons/Icon.svelte';

	interface Props {
		currentTrack: MusicKit.MediaItem | undefined;
		tracks: MusicKit.MediaItem[];
		isPlaying: boolean;
		index: number;
		onRemove: (position: number, count: number) => void;
		addAlbumToLibrary: (track: MusicKit.MediaItem) => void;
		children?: Snippet;
	}

	let { currentTrack, tracks, isPlaying, index, onRemove, addAlbumToLibrary, children }: Props = $props();

	let dropdownOpen = $state(false);

	let albumArtUrl = $derived(
		tracks?.[0]?.attributes?.artwork?.url
			? tracks[0].attributes.artwork.url.replace('{w}x{h}', '60x60')
			: ''
	);

	let albumName = $derived(tracks?.[0]?.attributes?.albumName ?? '');
	let artistName = $derived(tracks?.[0]?.attributes?.artistName ?? '');
	let trackCount = $derived(tracks?.length ?? 0);

	function toggleDropdown() {
		dropdownOpen = !dropdownOpen;
	}

	function closeDropdown() {
		dropdownOpen = false;
	}

	function handleAddAlbum() {
		if (tracks?.[0]) {
			addAlbumToLibrary(tracks[0]);
		}
		closeDropdown();
	}

	function handleRemove() {
		onRemove(index, tracks.length);
		closeDropdown();
	}
</script>

<div class="playlist-track-group" data-testid="playlist-track-group">
	<div class="album-header-container">
		<img
			style="height: 60px; width: 60px; vertical-align: top;"
			alt="album logo"
			src={albumArtUrl}
		/>
		<div class="album-header">
			<div class="dropdown" data-testid="dropdown-toggle">
				<CustomToggle onclick={toggleDropdown}>
					<span class="dropdown-icon"><Icon name="ellipsis-h" size={22} /></span>
				</CustomToggle>
				{#if dropdownOpen}
					<!-- svelte-ignore a11y_no_static_element_interactions -->
					<!-- svelte-ignore a11y_click_events_have_key_events -->
					<div class="dropdown-backdrop" onclick={closeDropdown}></div>
					<div class="dropdown-menu" data-testid="dropdown-menu">
						<button class="dropdown-item" onclick={handleAddAlbum}>
							<span class="menu-icon">
								<Icon name="folder-plus" size={16} />
							</span>
							<span>Add to your AppleMusic Library</span>
						</button>
						<button class="dropdown-item" onclick={handleRemove}>
							<span class="menu-icon">
								<Icon name="trash-alt" size={16} />
							</span>
							<span>Remove</span>
						</button>
					</div>
				{/if}
			</div>
			<h5 class="album-name">{albumName}</h5>
			<h6 class="artist-name">{artistName} ({trackCount})</h6>
		</div>
	</div>
	{#if children}
		{@render children()}
	{/if}
</div>
