// LastApple.Web/ClientApp/src/components/Player/StationPlayer.tsx
import * as React from 'react';
import musicKit from '../../musicKit';
import * as signalR from '@aspnet/signalr';
import {HubConnection} from '@aspnet/signalr';
import {Playlist} from './Playlist';
import lastfmApi from '../../restClients/LastfmApi';
import stationApi, {IStation} from '../../restClients/StationApi'
import environment from '../../Environment';
import {PlayerControls} from './PlayerControls';
import {Spinner} from 'react-bootstrap';
import {instance as mediaSessionManager} from '../../MediaSessionManager'
import {PlaybackStates} from '../../musicKitEnums';
import { LastfmContext } from '../../lastfm/LastfmContext';
import { AuthenticationState } from '../../authentication';
import MediaItemOptions = MusicKit.MediaItemOptions;

interface IPlayerProps {
    stationId: string;
}

interface IPlayerState {
    currentTrack?: MusicKit.MediaItem;
    tracks: MusicKit.MediaItem[];
    suppressEvents: boolean;
    isPlaying: boolean;
}

interface IAddTrackEvent {
    trackId: string;
    position: number;
}

export class StationPlayer extends React.Component<IPlayerProps, IPlayerState> {
    static contextType = LastfmContext;
    context: React.ContextType<typeof LastfmContext>;

    musicKit: MusicKit.MusicKitInstance;
    pendingEvents: IAddTrackEvent[] = [];
    station: IStation;
    requestedItems = 0;
    hubConnection: HubConnection;

    currentTrackScrobbled = false;

    private playbackStateSubscription: (x: MusicKit.Events['playbackStateDidChange']) => Promise<void>;

    constructor(props: IPlayerProps) {
        super(props);

        this.state = {
            tracks: [],
            suppressEvents: false,
            isPlaying: false
        };
    }

    async init() {
        if (!this.props.stationId)
            return;

        if (this.station && this.station.id === this.props.stationId) {
            return;
        }

        this.station = null;
        this.pendingEvents = [];

        if (!this.state.suppressEvents)
            this.setState({ suppressEvents: true });

        if (this.state.tracks.length)
            this.setState({ currentTrack: null, tracks: [] });

        if (this.musicKit) {
            await this.musicKit.stop();
            await this.musicKit.clearQueue();
        } else {
            this.musicKit = await musicKit.getInstance();

            await this.subscribeToStationEvents();

            this.playbackStateSubscription = async (x: MusicKit.Events['playbackStateDidChange']) => await this.handleStateChange(x);
            this.musicKit.addEventListener('playbackStateDidChange', this.playbackStateSubscription);
            this.musicKit.addEventListener('nowPlayingItemDidChange', async (event: MusicKit.Events['nowPlayingItemDidChange']) => {
                if (!event.item) {
                    return;
                }

                document.title = `${event.item.title} - ${event.item.artistName}`;
                this.currentTrackScrobbled = false;

                this.setState({ currentTrack: event.item });

                if (this.isScrobblingEnabled) {
                    await this.setNowPlaying(event.item);
                }

                if (this.station.isContinuous) {
                    this.topUp();
                }

                mediaSessionManager.updateSessionMetadata(event.item.artworkURL);
            });
            this.musicKit.addEventListener('playbackProgressDidChange', async (event: MusicKit.Events['playbackProgressDidChange']) => {
                if (this.currentTrackScrobbled) {
                    return;
                }

                if (event.progress < 0.9) {
                    return;
                }

                if (this.isScrobblingEnabled) {
                    await this.scrobble();
                    this.currentTrackScrobbled = true;
                }
            });

            mediaSessionManager.setNextHandler(() => this.switchNext());
            mediaSessionManager.setPrevHandler(() => this.switchPrev());
        }

        this.station = await stationApi.getStation(this.props.stationId);

        const batchItems = (arr: string[], size: number) =>
            arr.length > size
                ? [arr.slice(0, size), ...batchItems(arr.slice(size), size)]
                : [arr];

        for (let batch of batchItems(this.station.songIds, 300)) {
            if (batch.length) {
                const songs = await this.musicKit.api.music(`/v1/catalog/${this.musicKit.storefrontId}/songs`, { ids: batch });

                await this.appendTracksToQueue(songs.data.data);
            }
        }

        this.setState({ suppressEvents: false });
        if (this.musicKit.queue.items.length) {
            let context = new AudioContext();

            if (context.state === 'running') {
                await this.play();
            }
        }

        await this.addTracks(this.pendingEvents);
        this.pendingEvents = [];
    }

    async play() {
        await this.musicKit.play()
    }

    async appendTracksToQueue(tracks: MusicKit.Songs[]) {
        // @ts-ignore
        const currentTracks = this.state.tracks.concat(tracks);

        await this.musicKit.playLater({ songs: tracks.map(t => t.id) });
        this.setState({ tracks: currentTracks });
    }

    async componentDidUpdate(prevProps: IPlayerProps) {
        if (this.props.stationId !== prevProps.stationId)
            await this.init();
    }

    async componentDidMount() {
        await this.init();
    }

    componentWillUnmount() {
        this.hubConnection.off('trackAdded');
        this.musicKit.removeEventListener('playbackStateDidChange');
        this.musicKit.removeEventListener('playbackProgressDidChange');
        this.musicKit.removeEventListener('nowPlayingItemDidChange');
    }

    async subscribeToStationEvents() {
        this.hubConnection = new signalR.HubConnectionBuilder()
            .withUrl(`${environment.apiUrl}hubs`)
            .build();

        await this.hubConnection.start();

        this.hubConnection.on('trackAdded', async (stationId: string, trackId: string, position: number) => {
            if (stationId !== this.props.stationId) {
                return;
            }

            const event = { trackId, position };

            if (!this.station) {
                this.pendingEvents.push(event);
                return;
            }

            await this.addTracks([event]);
        });
    }

    async addTracks(addTrackEvents: IAddTrackEvent[]) {
        for (let event of addTrackEvents) {
            let existingItem = this.musicKit.queue.item(event.position);

            if (!existingItem) {
                let songs = await this.musicKit.api.music(`/v1/catalog/${this.musicKit.storefrontId}/songs`, { ids: [event.trackId] });

                if (songs.data.data.length === 0) {
                    console.warn(`Could not find song with id ${event.trackId}`);
                    return;
                }

                await this.appendTracksToQueue([songs.data.data[0]]);

                if (this.musicKit.queue.items.length === 1) {
                    await this.play();
                }

                return;
            }

            if (this.requestedItems > 0) {
                this.requestedItems--;
            }

            if (existingItem.id === event.trackId) {
                return;
            }

            console.warn(`Position ${event.position} already occupied by a different item.`);
        }
    }

    async handleStateChange(event: MusicKit.Events['playbackStateDidChange']) {
        if (!event) {
            return;
        }

        if (this.state.suppressEvents)
            return;

        const playing = event.state as unknown as PlaybackStates === PlaybackStates.playing;
        if (this.state.isPlaying !== playing) {
            this.setState({ isPlaying: playing });
        }
    }

    get isScrobblingEnabled() {
        return this.context.authentication.state === AuthenticationState.Authenticated && this.context.isScrobblingEnabled;
    }

    async topUp() {
        const itemsLeft = this.musicKit.queue.items.length - this.getCurrentQueuePosition() + this.requestedItems;
        const itemsToAdd = this.station.size - itemsLeft;

        if (itemsToAdd > 0) {
            this.requestedItems += itemsToAdd;
            await stationApi.topUp(this.props.stationId, this.station.definition.stationType, itemsToAdd);
        }
    }

    getCurrentQueuePosition() {
        const queuePosition = this.musicKit.queue.position;

        return queuePosition !== -1 ? queuePosition : 0;
    }

    async scrobble() {
        await lastfmApi.postScrobble(this.state.currentTrack.attributes.artistName,
                                     this.state.currentTrack.attributes.name,
                                     this.state.currentTrack.attributes.albumName,
                                     this.state.currentTrack.attributes.duration);
    }

    async setNowPlaying(item: MusicKit.MediaItem) {
        await lastfmApi.postNowPlaying(item.attributes.artistName,
                                       item.attributes.name,
                                       item.attributes.albumName,
                                       item.playbackDuration);
    }

    switchPrev = async() => {
        if (this.musicKit.isPlaying)
            this.musicKit.pause();

        await this.musicKit.skipToPreviousItem();
    };

    switchNext = async() => {
        if (this.musicKit.isPlaying)
            this.musicKit.pause();

        await this.musicKit.skipToNextItem();
    };

    getPlaylistPagingOffset(): number {
        if (this.station.isContinuous) {
            return this.getCurrentQueuePosition();
        }

        return 0;
    }

    render() {
        if (!this.station || !this.state.tracks.length)
            return <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '200px' }}>
                <Spinner animation="border" />
            </div>;

        return <div>
            <PlayerControls
                currentTrack={this.state.currentTrack}
                isPlaying={this.state.isPlaying}
                switchPrev={this.switchPrev}
                switchNext={this.switchNext}
                onPlayPause={this.handlePlayPause}
                isScrobblingEnabled={this.isScrobblingEnabled}
                onScrobblingSwitch={this.handleScrobblingSwitch}
                lastfmAuthenticated={this.context.authentication.state === AuthenticationState.Authenticated}
            />
            <Playlist
                tracks={this.state.tracks}
                isPlaying={this.state.isPlaying}
                offset={this.getPlaylistPagingOffset()}
                limit={this.station.isContinuous ? 10 : 1000}
                currentTrack={this.state.currentTrack}
                showAlbumInfo={this.station.isGroupedByAlbum}
                onTrackSwitch={this.handleTrackSwitched}
                onRemove={this.handleTracksRemoved}
            />
        </div>;
    }

    static getImageUrl(sourceUrl: string, size: number = 400) {
        return sourceUrl
            ? sourceUrl.replace('{w}x{h}', `${size}x${size}`).replace('2000x2000', `${size}x${size}`)
            : 'default-album-cover.png';
    }

    handlePlayPause = async () => {
        if (this.musicKit.isPlaying) {
            this.musicKit.pause();
            return;
        }

        await this.play();
    };

    handleTrackSwitched = async (index: number) => {
        const offset = this.getPlaylistPagingOffset() + index;
        const track = this.state.tracks[offset];

        if (this.state.currentTrack === track) {
            await this.handlePlayPause();

            return;
        }

        if (this.musicKit.isPlaying){
            this.musicKit.pause();
        }

        await this.musicKit.changeToMediaAtIndex(offset);

        this.setState({ currentTrack: track });

        if (this.station.isContinuous) {
            await this.topUp();
        }
    };

    handleTracksRemoved = async (position: number, count: number) => {
        const offset = this.getPlaylistPagingOffset() + position;

        this.state.tracks.splice(offset, count);
        this.setState({ tracks: this.state.tracks.slice() });

        await stationApi.deleteSongs(this.station.id, offset, count);

        if (this.station.isContinuous) {
            await this.topUp();
        }
    };

    handleScrobblingSwitch = (value: boolean) => {
        this.context.setIsScrobblingEnabled(value);
    }
}

// LastApple.Web/ClientApp-Svelte/src/lib/components/Player/StationPlayer.svelte
<script lang="ts">
	import { onDestroy } from 'svelte';
	import Playlist from './Playlist.svelte';
	import PlayerControls from './PlayerControls.svelte';
	import Spinner from '$lib/components/Spinner.svelte';
	import stationApi, { type IStation } from '$lib/api/stationApi';
	import lastfmApi from '$lib/api/lastfmApi';
	import musicKit from '$lib/services/musicKit';
	import { lastfmAuthState } from '$lib/stores/lastfmAuth';
	import { AuthenticationState } from '$lib/models/authenticationState';
	import { PlaybackStates } from '$lib/services/musicKitEnums';
	import { HubConnectionBuilder, type HubConnection } from '@microsoft/signalr';
	import environment from '$lib/services/environment';

	interface Props {
		stationId: string;
	}

	interface IAddTrackEvent {
		trackId: string;
		position: number;
	}

	let { stationId }: Props = $props();

	let station: IStation | null = $state(null);
	let tracks: MusicKit.MediaItem[] = $state([]);
	let currentTrack: MusicKit.MediaItem | undefined = $state(undefined);
	let isPlaying = $state(false);
	let suppressEvents = $state(false);
	let isLoading = $state(true);

	let musicKitInstance: MusicKit.MusicKitInstance | null = null;
	let hubConnection: HubConnection | null = null;
	let pendingEvents: IAddTrackEvent[] = [];
	let currentTrackScrobbled = false;
	let requestedItems = 0;
	let isFirstTime = true;

	let isScrobblingEnabled = $derived(
		$lastfmAuthState.state === AuthenticationState.Authenticated && $lastfmAuthState.isScrobblingEnabled
	);
	let lastfmAuthenticated = $derived($lastfmAuthState.state === AuthenticationState.Authenticated);

	function getCurrentQueuePosition(): number {
		if (!musicKitInstance) return 0;
		const pos = musicKitInstance.queue.position;
		return pos !== -1 ? pos : 0;
	}

	function getPlaylistPagingOffset(): number {
		if (station?.isContinuous) {
			return getCurrentQueuePosition();
		}
		return 0;
	}

	function batchItems<T>(arr: T[], size: number): T[][] {
		return arr.length > size ? [arr.slice(0, size), ...batchItems(arr.slice(size), size)] : [arr];
	}

	async function subscribeToStationEvents() {
		if (hubConnection) return;

		const apiUrl = environment.apiUrl;
		hubConnection = new HubConnectionBuilder().withUrl(`${apiUrl}hubs`).build();

		await hubConnection.start();

		hubConnection.on('trackAdded', async (trackStationId: string, trackId: string, position: number) => {
			if (trackStationId !== stationId) return;

			const event: IAddTrackEvent = { trackId, position };
			await handleTrackAdded(event);
		});
	}

	async function handleTrackAdded(event: IAddTrackEvent) {
		if (!station) {
			pendingEvents.push(event);
			return;
		}

		if (!musicKitInstance) return;

		const existingItem = musicKitInstance.queue.item(event.position);

		if (!existingItem) {
			const songs = await musicKitInstance.api.music(
				`/v1/catalog/${musicKitInstance.storefrontId}/songs`,
				{ ids: [event.trackId] }
			);

			if (songs.data.data.length === 0) {
				console.warn(`Could not find song with id ${event.trackId}`);
				return;
			}

			const song = songs.data.data[0];
			await musicKitInstance.playLater({ songs: [song.id] });
			tracks = [...tracks, song as unknown as MusicKit.MediaItem];

			if (musicKitInstance.queue.items.length === 1) {
				await musicKitInstance.play();
			}
			return;
		}

		if (requestedItems > 0) {
			requestedItems--;
		}

		if (existingItem.id === event.trackId) {
			return;
		}

		console.warn(`Position ${event.position} already occupied by a different item.`);
	}

	async function scrobble(track: MusicKit.MediaItem) {
		if (!isScrobblingEnabled) return;

		await lastfmApi.scrobble(
			track.attributes.name,
			track.attributes.artistName,
			track.attributes.albumName,
			Math.floor(Date.now() / 1000)
		);
	}

	async function setNowPlaying(item: MusicKit.MediaItem) {
		if (!isScrobblingEnabled) return;

		await lastfmApi.updateNowPlaying(
			item.attributes.name,
			item.attributes.artistName,
			item.attributes.albumName
		);
	}

	function handleScrobblingSwitch(enabled: boolean) {
		lastfmAuthState.setIsScrobblingEnabled(enabled);
	}

	async function topUp() {
		if (!station || !musicKitInstance) return;

		const queueLength = musicKitInstance.queue.items.length;
		const itemsLeft = queueLength - getCurrentQueuePosition() + requestedItems;
		const itemsToAdd = station.size - itemsLeft;

		if (itemsToAdd > 0) {
			requestedItems += itemsToAdd;
			await stationApi.topUp(stationId, station.definition.stationType, itemsToAdd);
		}
	}

	async function handleStateChange(event: MusicKit.Events['playbackStateDidChange']) {
		if (!event || suppressEvents) return;

		const playing = (event.state as unknown as PlaybackStates) === PlaybackStates.playing;
		if (isPlaying !== playing) {
			isPlaying = playing;
		}
	}

	async function handleNowPlayingItemChange(event: MusicKit.Events['nowPlayingItemDidChange']) {
		if (!event.item) return;

		document.title = `${event.item.title} - ${event.item.artistName}`;
		currentTrackScrobbled = false;
		currentTrack = event.item;

		if (isScrobblingEnabled) {
			await setNowPlaying(event.item);
		}

		if (station?.isContinuous) {
			await topUp();
		}
	}

	async function handlePlaybackProgressChange(event: MusicKit.Events['playbackProgressDidChange']) {
		if (currentTrackScrobbled || event.progress < 0.9) return;

		if (currentTrack && isScrobblingEnabled) {
			await scrobble(currentTrack);
			currentTrackScrobbled = true;
		}
	}

	async function handlePlayPause() {
		if (!musicKitInstance) return;

		if (musicKitInstance.isPlaying) {
			musicKitInstance.pause();
			return;
		}

		await musicKitInstance.play();
	}

	async function skipToPreviousItem() {
		if (!musicKitInstance) return;
		if (musicKitInstance.isPlaying) {
			musicKitInstance.pause();
		}
		await musicKitInstance.skipToPreviousItem();
	}

	async function skipToNextItem() {
		if (!musicKitInstance) return;
		if (musicKitInstance.isPlaying) {
			musicKitInstance.pause();
		}
		await musicKitInstance.skipToNextItem();
	}

	async function handleTrackSwitched(index: number) {
		if (!station || !musicKitInstance) return;

		const offset = getPlaylistPagingOffset() + index;
		const track = tracks[offset];

		if (currentTrack && track && currentTrack.id === track.id) {
			await handlePlayPause();
			return;
		}

		if (musicKitInstance.isPlaying) {
			musicKitInstance.pause();
		}
		await musicKitInstance.changeToMediaAtIndex(offset);
		currentTrack = track;

		if (station.isContinuous) {
			await topUp();
		}
	}

	async function handleTracksRemoved(position: number, count: number) {
		if (!station) return;

		const offset = getPlaylistPagingOffset() + position;
		const newTracks = [...tracks];
		newTracks.splice(offset, count);
		tracks = newTracks;

		await stationApi.deleteSongs(station.id, offset, count);

		if (station.isContinuous) {
			await topUp();
		}
	}

	async function init() {
		if (!stationId) return;

		// Return early if this station is already loaded (preserves player state when switching tabs)
		if (station && station.id === stationId) {
			return;
		}

		isLoading = true;
		suppressEvents = true;
		currentTrack = undefined;
		tracks = [];

		musicKitInstance = await musicKit.getInstance();

		if (isFirstTime) {
			isFirstTime = false;
			await subscribeToStationEvents();

			musicKitInstance.addEventListener('playbackStateDidChange', handleStateChange);
			musicKitInstance.addEventListener('nowPlayingItemDidChange', handleNowPlayingItemChange);
			musicKitInstance.addEventListener('playbackProgressDidChange', handlePlaybackProgressChange);
		} else {
			musicKitInstance.stop();
			await musicKitInstance.clearQueue();
		}

		station = await stationApi.getStation(stationId);
		if (!station) {
			isLoading = false;
			return;
		}

		let isFirstBatch = true;
		for (const batch of batchItems(station.songIds, 300)) {
			if (batch.length) {
				const response = await musicKitInstance.api.music(
					`/v1/catalog/${musicKitInstance.storefrontId}/songs`,
					{ ids: batch }
				);
				const songs = response.data.data as unknown as MusicKit.MediaItem[];

				if (isFirstBatch) {
					await musicKitInstance.setQueue({ songs: songs.map((s) => s.id) });
					isFirstBatch = false;
				} else {
					await musicKitInstance.playLater({ songs: songs.map((s) => s.id) });
				}
				tracks = [...tracks, ...songs];
			}
		}

		suppressEvents = false;
		isLoading = false;

		const queueItems = musicKitInstance.queue.items;
		if (queueItems.length) {
			const context = new AudioContext();
			if (context.state === 'running') {
				await musicKitInstance.play();
			}
		}

		if (pendingEvents.length > 0) {
			for (const event of pendingEvents) {
				await handleTrackAdded(event);
			}
			pendingEvents = [];
		}
	}

	onDestroy(() => {
		hubConnection.off('trackAdded');
		musicKitInstance.removeEventListener('playbackStateDidChange', handleStateChange);
		musicKitInstance.removeEventListener('playbackProgressDidChange', handlePlaybackProgressChange);
		musicKitInstance.removeEventListener('nowPlayingItemDidChange', handleNowPlayingItemChange);
	});

	// React to stationId changes (also runs on mount)
	$effect(() => {
		if (stationId) {
			init();
		}
	});
</script>

<div class="station-player" data-testid="station-player">
	{#if isLoading || !station || !tracks.length}
		<div style="display: flex; align-items: center; justify-content: center; height: 200px;">
			<Spinner />
		</div>
	{:else}
		<div data-testid="player-controls">
			<PlayerControls
				{currentTrack}
				{isPlaying}
				switchPrev={skipToPreviousItem}
				switchNext={skipToNextItem}
				onPlayPause={handlePlayPause}
				{isScrobblingEnabled}
				onScrobblingSwitch={handleScrobblingSwitch}
				{lastfmAuthenticated}
			/>
		</div>
		<div data-testid="playlist">
			<Playlist
				{tracks}
				{isPlaying}
				offset={getPlaylistPagingOffset()}
				limit={station.isContinuous ? 10 : 1000}
				{currentTrack}
				showAlbumInfo={station.isGroupedByAlbum}
				onTrackSwitch={handleTrackSwitched}
				onRemove={handleTracksRemoved}
			/>
		</div>
		<div data-testid="track-count" style="display: none;">{tracks.length}</div>
	{/if}
</div>
