// LastApple.Web/ClientApp-Svelte/src/lib/components/LastfmAvatar.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { lastfmAuthStore } from '$lib/stores/lastfmAuth';
	import { AuthenticationState } from '$lib/models/authenticationState';
	import lastfmLogo from '$lib/images/lastfm-logo.png';

	function handleClick(event: MouseEvent) {
		if ($lastfmAuthStore.user) {
			return;
		}
		event.preventDefault();
		goto('/settings');
	}

	let avatarUrl = $derived($lastfmAuthStore.user?.avatar?.[0] ?? lastfmLogo);
	let profileUrl = $derived($lastfmAuthStore.user ? `https://www.last.fm/user/${$lastfmAuthStore.user.name}` : null);
	let displayName = $derived($lastfmAuthStore.user?.name ?? 'Log in');
</script>

<div class="lastfm-avatar" data-testid="lastfm-avatar">
	{#if $lastfmAuthStore.state === AuthenticationState.Loading}
		<div style="margin-right: 15px;">
			<div class="spinner-border" style="width: 20px; height: 20px;" role="status">
				<span class="visually-hidden">Loading...</span>
			</div>
		</div>
	{:else}
		<a
			style="color: #DDD; text-decoration: none; display: flex; flex-direction: column; align-items: center;"
			class="lastfm-profile"
			href={profileUrl}
			title="Open lastfm profile"
			target="_blank"
			rel="noopener noreferrer"
			onclick={handleClick}
		>
			<img alt="" style="border-radius: 20px;" src={avatarUrl} />
			<span>{displayName}</span>
		</a>
	{/if}
</div>

// LastApple.Web/ClientApp/src/components/LastfmAvatar.tsx
import React from "react";
import { Spinner } from 'react-bootstrap';
import lastfmLogo from '../images/lastfm-logo.png'
import { useHistory } from "react-router";
import { useLastfmContext } from '../lastfm/LastfmContext';
import { AuthenticationState } from '../authentication';

export const LastfmAvatar = () => {
    const lastfmContext = useLastfmContext();
    const history = useHistory();

    const onClick = React.useCallback(
        () => {
            if (lastfmContext.authentication.user !== undefined)
                return;

            history.push('/settings');
        },
        [history, lastfmContext.authentication.user]
    );

    if (lastfmContext.authentication.state === AuthenticationState.Loading) {
        return (
            <div style={{ marginRight: '15px' }}>
                <Spinner animation="border" style={{ width: '20px', height: '20px' }} />
            </div>
        );
    }

    return (
        <div>
            <a style={{
                color: '#DDD',
                textDecoration: 'none',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center'
            }}
               className='lastfm-profile'
               href={lastfmContext.authentication.user && `https://www.last.fm/user/${lastfmContext.authentication.user.name}`}
               title={'Open lastfm profile'}
               target="_blank" rel="noopener noreferrer"
               onClick={onClick}>
                <img alt={''} style={{ borderRadius: '20px' }} src={lastfmContext.authentication.user?.avatar[0] ?? lastfmLogo} />
                <span>{lastfmContext.authentication.user?.name ?? 'Log in'}</span>
            </a>
        </div>
    );
}
