// LastApple.Web/ClientApp/src/routes/settings/+page.svelte
<script lang="ts">
  import { appleStore } from '$lib/stores/apple';
  import { lastfmStore } from '$lib/stores/lastfm';
  import { AuthenticationState } from '$lib/types/authentication';
  import { authorizeAppleMusic, unauthorizeAppleMusic } from '$lib/services/AppleAuthService';
  import { authorizeLastfm, unauthorizeLastfm } from '$lib/services/LastfmAuthService';

  $: isAppleAuthenticated = $appleStore.authenticationState === AuthenticationState.Authenticated;
  $: isLastfmAuthenticated = $lastfmStore.authenticationState === AuthenticationState.Authenticated;
  $: isLoading = $appleStore.authenticationState === AuthenticationState.Loading || 
                 $lastfmStore.authenticationState === AuthenticationState.Loading;

  async function toggleAppleAuthentication() {
    if (isAppleAuthenticated) {
      await unauthorizeAppleMusic();
    } else {
      await authorizeAppleMusic();
    }
  }

  async function toggleLastfmAuthentication() {
    if (isLastfmAuthenticated) {
      await unauthorizeLastfm();
    } else {
      await authorizeLastfm();
    }
  }
</script>

{#if isLoading}
  <div class="loading-container">
    <div class="spinner-border" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
{:else}
  <div class="settings-container">
    <div class="settings-header">Connected accounts</div>
    
    <div class="settings-row">
      <img class="service-logo" src="/apple-music-logo.png" alt="Apple Music Logo" />
      <div class="service-name">Apple Music</div>
      <label class="toggle-switch">
        <input 
          type="checkbox" 
          checked={isAppleAuthenticated}
          on:change={toggleAppleAuthentication}
          role="switch"
        />
        <span class="slider"></span>
      </label>
    </div>

    <div class="settings-row">
      <img class="service-logo" src="/lastfm-logo.png" alt="Last.fm logo" />
      <div class="service-name">Last.fm</div>
      <label class="toggle-switch">
        <input 
          type="checkbox" 
          checked={isLastfmAuthenticated}
          on:change={toggleLastfmAuthentication}
          role="switch"
        />
        <span class="slider"></span>
      </label>
    </div>
  </div>
{/if}

<style>
  .loading-container {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 200px;
  }

  .settings-container {
    display: flex;
    flex-direction: column;
  }

  .settings-header {
    background: #0E0E0E;
    padding: 10px 25px;
  }

  .settings-row {
    flex: 1;
    display: flex;
    padding: 20px;
    align-items: center;
    border-bottom: 1px solid #333;
  }

  .service-logo {
    height: 30px;
    margin-right: 15px;
  }

  .service-name {
    flex: 1;
  }

  /* Custom toggle switch styles (replacing react-switch) */
  .toggle-switch {
    position: relative;
    display: inline-block;
    width: 44px;
    height: 22px;
  }

  .toggle-switch input {
    opacity: 0;
    width: 0;
    height: 0;
  }

  .slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #888;
    transition: .4s;
    border-radius: 22px;
  }

  .slider:before {
    position: absolute;
    content: "";
    height: 16px;
    width: 16px;
    left: 3px;
    bottom: 3px;
    background-color: white;
    transition: .4s;
    border-radius: 50%;
  }

  input:checked + .slider {
    background-color: #8e0000;
  }

  input:checked + .slider:before {
    transform: translateX(22px);
  }
</style>

// LastApple.Web/ClientApp/src/components/Settings.tsx
import React from "react";
import appleMusicLogo from '../images/apple-music-logo.png';
import lastfmLogo from '../images/lastfm-logo.png';
import { Spinner } from 'react-bootstrap';
import ReactSwitch from "react-switch";
import { AuthenticationState } from '../authentication';
import { useAppleContext } from '../apple/AppleContext';
import { useLastfmContext } from '../lastfm/LastfmContext';
import { loginApple as serviceLoginApple, logoutApple as serviceLogoutApple } from '../apple/appleAuthentication';
import { loginLastfm as serviceLoginLastfm, logoutLastfm as serviceLogoutLastfm } from '../lastfm/lastfmAuthentication';

const rowStyles: React.CSSProperties = { flex: 1, display: 'flex', padding: '20px', alignItems: 'center', borderBottom: '1px solid #333' };
const logoStyles: React.CSSProperties = { height: '30px', marginRight: '15px' };

export const Settings: React.FunctionComponent = () => {
    const appleContext = useAppleContext();
    const lastfmContext = useLastfmContext();

    const loginApple = React.useCallback(
        async () => await serviceLoginApple(appleContext.authentication),
        [appleContext.authentication]
    );

    const logoutApple = React.useCallback(
        async () => await serviceLogoutApple(appleContext.authentication),
        [appleContext.authentication]
    );

    const loginLastfm = React.useCallback(
        async () => await serviceLoginLastfm(lastfmContext.authentication),
        [lastfmContext.authentication]
    );

    const logoutLastfm = React.useCallback(
        async () => await serviceLogoutLastfm(lastfmContext.authentication),
        [lastfmContext.authentication]
    );

    const isAppleAuthenticated = appleContext.authentication.state === AuthenticationState.Authenticated;
    const isLastfmAuthenticated = lastfmContext.authentication.state === AuthenticationState.Authenticated;

    const toggleAppleAuthentication = React.useCallback(
        async () =>
            isAppleAuthenticated
                ? await logoutApple()
                : await loginApple(),
        [isAppleAuthenticated, loginApple, logoutApple]
    );

    const toggleLastfmAuthentication = React.useCallback(
        async () =>
            isLastfmAuthenticated
                ? await logoutLastfm()
                : await loginLastfm(),
        [isLastfmAuthenticated, loginLastfm, logoutLastfm]
    );

    if (appleContext.authentication.state === AuthenticationState.Loading || lastfmContext.authentication.state === AuthenticationState.Loading)
        return <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '200px' }}>
            <Spinner animation="border" role="status" />
        </div>;

    return (
        <div style={{ display: 'flex', flexDirection: 'column' }}>
            <div style={{ background: '#0E0E0E', padding: '10px 25px'  }}>Connected accounts</div>
            <div style={rowStyles}>
                <img style={logoStyles} src={appleMusicLogo} alt='Apple Music Logo' />
                <div style={{ flex: 1 }}>Apple Music</div>
                <ReactSwitch
                    checked={isAppleAuthenticated}
                    onChange={toggleAppleAuthentication}
                    uncheckedIcon={false}
                    checkedIcon={false}
                    height={22}
                    width={44}
                    offColor={'#888'}
                    onColor={'#8e0000'}
                    role="switch"
                />
            </div>
            <div style={rowStyles}>
                <img style={logoStyles} src={lastfmLogo} alt='Last.fm logo' />
                <div style={{ flex: 1 }}>Last.fm</div>
                <ReactSwitch
                    checked={isLastfmAuthenticated}
                    onChange={toggleLastfmAuthentication}
                    uncheckedIcon={false}
                    checkedIcon={false}
                    height={22}
                    width={44}
                    offColor={'#888'}
                    onColor={'#8e0000'}
                    role="switch"
                />
            </div>
        </div>
    );
};
