// LastApple.Web/ClientApp/src/lib/components/StationDescriptor.svelte
<script lang="ts">
	import type { IStationDefinition } from '$lib/models/stationDefinition';
	import type { Component } from 'svelte';
	import { goto } from '$app/navigation';
	import Icon from "$lib/components/Icons/Icon.svelte";

	interface Props {
		definition: IStationDefinition;
		StationComponent: Component;
	}

	let { definition, StationComponent }: Props = $props();

	let triggerCreate = $state(false);
	let optionsValid = $state(false);

	function handleStationCreated(stationId: string) {
		goto(`/station/${stationId}`);
	}

	function handleOptionsChanged(valid: boolean) {
		optionsValid = valid;
	}

	function handleCreateClick() {
		if (!optionsValid) return;
		triggerCreate = true;
	}

	let color = {
		valid: '#8e0000',
		default: '#333'
	}
</script>

<div class="station-descriptor" style="margin: 5px; padding: 15px; background: #00000099; cursor: pointer; flex: 1;">
	<h4 style="margin-top: 10px; font-size: 15px; text-align: center; color: #EEE;">{definition.title}</h4>
	<div style="color: #AAA;">{definition.description}</div>
	<div style="display: flex; align-items: center;">
		<StationComponent
			{triggerCreate}
			onStationCreated={handleStationCreated}
			onOptionsChanged={handleOptionsChanged}
		/>
		<button onclick={handleCreateClick}
			aria-label="Create station"
			style="color: {optionsValid ? color.valid : color.default}; cursor: pointer; background: none; border: none; padding: 0;">
			<Icon name="arrow-right-in-circle" size={32} />
		</button>
	</div>
</div>

// LastApple.Web/ClientApp/src/components/StationDescriptor.tsx
import React, { Component } from 'react';
import { IStationDefinition } from './IStationDefinition';
import { Redirect } from 'react-router';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowCircleRight } from '@fortawesome/free-solid-svg-icons';
import { IStationParams } from './IStationParams';

interface DescriptorProps {
    definition: IStationDefinition;
    StationComponent: React.ComponentType<IStationParams>;
}

const descriptorStyles: React.CSSProperties = {
    margin: '5px',
    padding: '15px',
    background: '#00000099',
    cursor: 'pointer',
    flex: 1
};
const descriptorTitleStyles: React.CSSProperties = {
    marginTop: '10px',
    fontSize: '15px',
    textAlign: 'center',
    color: '#EEE'
};

export class StationDescriptor extends Component<DescriptorProps, { isValid: boolean, triggerStationCreate: boolean, createdStationId: string }> {
    constructor(props) {
        super(props);

        this.state = {
            isValid: false,
            triggerStationCreate: false,
            createdStationId: null
        };
    }

    render(): React.ReactNode {
        if (this.state.createdStationId) {
            return <Redirect to={`/station/${this.state.createdStationId}`}/>
        }

        return <div className={'station-descriptor'} style={descriptorStyles}>
            <h4 style={descriptorTitleStyles}>{this.props.definition.title}</h4>
                <div style={{ color: '#AAA' }}>{this.props.definition.description}</div>
                <div style={{ display: 'flex', alignItems: 'center' }}>
                    <this.props.StationComponent
                        triggerCreate={this.state.triggerStationCreate}
                        onStationCreated={id => this.setState({ createdStationId: id })}
                        onOptionsChanged={x => this.handleOptionsChanged(x)} />
                    <span onClick={() => this.handleStationCreate()}>
                        <FontAwesomeIcon style={{ color: this.state.isValid ? '#8e0000' : '#333' }} icon={faArrowCircleRight} size='2x' />
                    </span>
                </div>
            </div>;
    }

    handleStationCreate() {
        if (!this.state.isValid)
            return;

        this.setState({ triggerStationCreate: true });
    }

    handleOptionsChanged(isValid) {
        if (this.state.isValid !== isValid) {
            this.setState({ isValid });
        }
    }
}
