// LastApple.Web/ClientApp/src/components/Stations/Tag.tsx
import React, { useState, useEffect } from "react";
import { IStationParams } from "../IStationParams";
import stationApi from "../../restClients/StationApi";

export const Tag: React.FC<IStationParams> = ({ triggerCreate, onStationCreated, onOptionsChanged }) => {
    const [tagName, setTagName] = useState<string | null>(null);

    useEffect(() => {
        const createStation = async () => {
            if (triggerCreate) {
                const station = await stationApi.postStation('tags', tagName);
                onStationCreated(station.id);
            }
        };

        createStation();
    }, [triggerCreate, tagName, onStationCreated]);

    const handleChanged = (tag: string) => {
        setTagName(tag);
        onOptionsChanged(!!tag);
    };

    return <div className={'station-parameters'}>
        <input style={{ width: '100%', padding: '6px 12px', borderWidth: '1px' }}
               placeholder={'Rock...'}
               type={'text'}
               onChange={e => handleChanged(e.currentTarget.value)}/>
    </div>
};

Tag.Definition = {
    title: 'Tag',
    description: 'A station consisting of tracks related to a last.fm tag.',
    type: Tag
};

// LastApple.Web/ClientApp/src/lib/components/Stations/Tag.svelte
<script lang="ts" module>
	import type { IStationDefinition } from '$lib/models/stationDefinition';

	export const Definition: IStationDefinition = {
		title: 'Tag',
		description: 'A station consisting of tracks related to a last.fm tag.',
		type: null as any
	};
</script>

<script lang="ts">
	import type { IStationParams } from '$lib/models/stationParams';
	import stationApi from '$lib/api/stationApi';

	interface Props extends IStationParams {}

	let { triggerCreate, onStationCreated, onOptionsChanged }: Props = $props();

	let tagName = $state<string | null>(null);

	// Call onOptionsChanged based on tag input
	$effect(() => {
		onOptionsChanged(!!tagName);
	});

	// Handle station creation when triggerCreate becomes true
	$effect(() => {
		if (triggerCreate && tagName) {
			createStation();
		}
	});

	async function createStation() {
		const station = await stationApi.postStation('tags', tagName);
		onStationCreated(station.id);
	}

	function handleChanged(event: Event) {
		const target = event.target as HTMLInputElement;
		const value = target.value.trim();
		tagName = value || null;
	}
</script>

<div class="station-parameters">
	<input
		style="width: 100%; padding: 6px 12px; border-width: 1px;"
		placeholder="Rock..."
		type="text"
		oninput={handleChanged}
	/>
</div>
