// LastApple.Web/ClientApp-Svelte/src/lib/components/Stations/MyLibrary.svelte
<script lang="ts" module>
	import type { IStationDefinition } from '$lib/models/stationDefinition';

	export const Definition: IStationDefinition = {
		title: 'My last.fm Library',
		description: 'A continuous station based on your last.fm library.',
		type: null as any
	};
</script>

<script lang="ts">
	import type { IStationParams } from '$lib/models/stationParams';
	import { lastfmAuthStore } from '$lib/stores/lastfmAuth';
	import { AuthenticationState } from '$lib/models/authenticationState';
	import stationApi from '$lib/api/stationApi';

	interface Props extends IStationParams {}

	let { triggerCreate, onStationCreated, onOptionsChanged }: Props = $props();

	$effect(() => {
		onOptionsChanged($lastfmAuthStore.state === AuthenticationState.Authenticated);
	});

	$effect(() => {
		if (triggerCreate) {
			createStation();
		}
	});

	async function createStation() {
		const station = await stationApi.postStation('lastfmlibrary', 'my');
		onStationCreated(station.id);
	}

	let showWarning = $derived($lastfmAuthStore.state === AuthenticationState.Unauthenticated);
</script>

<div class="station-parameters" style="display: flex; flex: 1;">
	{#if showWarning}
		<div style="margin: 10px 10px 10px 0; color: #ffc123;">
			Log in to last.fm to listen to your library.
		</div>
	{/if}
	<div style="flex: 1; height: 54px;"></div>
</div>

// LastApple.Web/ClientApp/src/components/Stations/MyLibrary.tsx
import React, { useContext, useEffect } from "react";
import { IStationParams } from "../IStationParams";
import stationApi from "../../restClients/StationApi";
import { LastfmContext } from '../../lastfm/LastfmContext';
import { AuthenticationState } from '../../authentication';

export const MyLibrary: React.FC<IStationParams> = ({ triggerCreate, onStationCreated, onOptionsChanged }) => {
    const context = useContext(LastfmContext);

    useEffect(() => {
        onOptionsChanged(context.authentication.state === AuthenticationState.Authenticated);
    }, [context.authentication.state, onOptionsChanged]);

    useEffect(() => {
        const createStation = async () => {
            if (triggerCreate) {
                const station = await stationApi.postStation('lastfmlibrary', 'my');
                onStationCreated(station.id);
            }
        };

        createStation();
    }, [triggerCreate, onStationCreated]);

    const showWarning = context.authentication.state === AuthenticationState.Unauthenticated;
    
    return <div className='station-parameters' style={{ display: 'flex', flex: 1 }}>
        <div style={{ margin: '10px 10px 10px 0', color: '#ffc123', display: showWarning ? 'block' : 'none' }}>Log in to last.fm to listen to your library.</div>
        <div style={{ flex: 1, height: '54px' }}></div>
    </div>;
};

MyLibrary.Definition = {
    title: 'My last.fm Library',
    description: 'A continuous station based on your last.fm library.',
    type: MyLibrary
};
