// LastApple.Web/ClientApp-Svelte/src/lib/components/Stations/SimilarArtists.svelte
<script lang="ts" module>
	import type { IStationDefinition } from '../IStationDefinition';
	
	export const Definition: IStationDefinition = {
		title: 'Similar Artists',
		description: 'A station containing an artist and similar performers.',
		type: null as any
	};
</script>

<script lang="ts">
	import type { IStationParams } from '../IStationParams';
	import Search from '../Search.svelte';
	import lastfmApi from '$lib/api/lastfmApi';
	import stationApi from '$lib/api/stationApi';
	
	interface Props extends IStationParams {}
	
	let { triggerCreate, onStationCreated, onOptionsChanged }: Props = $props();
	
	let artist = $state<string | null>(null);
	
	// Call onOptionsChanged based on artist selection
	$effect(() => {
		onOptionsChanged(artist !== null);
	});
	
	// Handle station creation when triggerCreate becomes true
	$effect(() => {
		if (triggerCreate && artist) {
			createStation();
		}
	});
	
	async function createStation() {
		const station = await stationApi.postStation('similarartists', artist);
		onStationCreated(station.id);
	}
	
	async function search(term: string): Promise<string[]> {
		const results = await lastfmApi.searchArtist(term);
		return results.map((x: { name: string }) => x.name);
	}
	
	function handleChanged(artists: string[]) {
		const selectedArtist = artists[0];
		artist = selectedArtist || null;
	}
</script>

<div class="station-parameters">
	<Search 
		{search}
		onChanged={handleChanged}
		placeholder="Placebo..."
	/>
</div>

// LastApple.Web/ClientApp/src/components/Stations/SimilarArtists.tsx
import React, { Component } from "react";
import { Search } from "../Search";
import { IStationParams } from "../IStationParams";
import stationApi from "../../restClients/StationApi";
import lastfmApi from "../../restClients/LastfmApi";

export class SimilarArtists extends Component<IStationParams, { artist: string }> {
    constructor(props) {
        super(props);

        this.state = {
            artist: null
        };
    }

    async componentDidUpdate() {
        if (this.props.triggerCreate) {
            const station = await stationApi.postStation('similarartists', this.state.artist);

            this.props.onStationCreated(station.id);
        }
    }

    async search(term: string) {
        const results = await lastfmApi.searchArtist(term);

        return results.map(x => x.name);
    }

    render(): React.ReactNode {
        return <div className='station-parameters'>
            <Search<string> search={term => this.search(term)}
                                       onChanged={artist => this.handleChanged(artist)}
                                       placeholder={'Placebo...'}/>
        </div>;
    }

    handleChanged(artist: string) {
        this.setState({ artist: artist });
        this.props.onOptionsChanged(!!artist);
    }

    static Definition = {
        title: 'Similar Artists',
        description: 'A station containing an artist and similar performers.',
        type: SimilarArtists
    };
}
