// LastApple.Web/ClientApp/src/lib/components/Player/CustomToggle.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		onclick?: (event: MouseEvent) => void;
		children?: Snippet;
	}

	let { onclick, children }: Props = $props();

	function handleClick(e: MouseEvent) {
		e.preventDefault();
		onclick?.(e);
	}
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="custom-toggle" style="cursor: pointer;" onclick={handleClick}>
	{#if children}
		{@render children()}
	{/if}
</div>

// LastApple.Web/ClientApp/src/components/Player/CustomToggle.tsx
import * as React from "react";

export class CustomToggle extends React.Component<{ onClick(e: any): any }, any> {
    constructor(props, context) {
        super(props, context);

        this.handleClick = this.handleClick.bind(this);
    }

    handleClick(e) {
        e.preventDefault();

        this.props.onClick(e);
    }

    render() {
        return <div onClick={this.handleClick} style={{ cursor: 'pointer' }}>
            {this.props.children}
        </div>;
    }
}
