// LastApple.Web/ClientApp/src/lib/components/Player/PlayerHeader.svelte
<script lang="ts">
    interface Props {
        currentTrack: MusicKit.MediaItem | undefined;
        isScrobblingEnabled: boolean;
        onScrobblingSwitch: (enabled: boolean) => void;
        lastfmAuthenticated: boolean;
    }

    let { currentTrack, isScrobblingEnabled, onScrobblingSwitch, lastfmAuthenticated }: Props = $props();

    function handleToggle(e: Event) {
        const target = e.target as HTMLInputElement;
        onScrobblingSwitch(target.checked);
    }
</script>

<div class="player-header">
    <div class="scrobble-container">
        <div class="scrobble-label">Scrobble</div>
        <label class="switch">
            <input
                type="checkbox"
                role="switch"
                aria-label="scrobbling"
                checked={isScrobblingEnabled}
                disabled={!lastfmAuthenticated}
                onchange={handleToggle}
            />
            <span class="slider" class:checked={isScrobblingEnabled}></span>
        </label>
    </div>
    {#if currentTrack?.attributes}
        <h5 class="track-name">{currentTrack.attributes.name}</h5>
        <h6 class="track-info">{currentTrack.attributes.artistName} - {currentTrack.attributes.albumName}</h6>
    {/if}
</div>

// LastApple.Web/ClientApp/src/components/Player/PlayerHeader.tsx
import ReactSwitch from "react-switch";
import * as React from "react";

export type PlayerHeaderProps = { currentTrack: MusicKit.MediaItem, isScrobblingEnabled: boolean, onScrobblingSwitch(enabled: boolean): void, lastfmAuthenticated: boolean };

export const PlayerHeader = (props: PlayerHeaderProps) =>
    <div style={{
        padding: '5px 20px',
        background: '#00000099',
        position: 'absolute',
        left: 0,
        top: 0,
        right: 0
    }}>
        <div style={{
            float: 'right'
        }}>
            <div style={{ marginBottom: '5px' }}>Scrobble</div>
            <ReactSwitch
                checked={props.isScrobblingEnabled}
                onChange={x => props.onScrobblingSwitch(x)}
                uncheckedIcon={false}
                checkedIcon={false}
                height={22}
                width={44}
                offColor={'#222'}
                onColor={'#8e0000'}
                disabled={!props.lastfmAuthenticated}
            />
        </div>
        <h5 style={{
            textAlign: 'left',
            marginTop: '0.7rem'
        }}>{props.currentTrack.attributes.name}</h5>
        <h6 style={{
            textAlign: 'left',
            margin: '0.7rem 0 0.7rem'
        }}>{`${props.currentTrack.attributes.artistName} - ${props.currentTrack.attributes.albumName}`}</h6>
    </div>;
