// LastApple.Web/ClientApp/src/lib/components/Player/PlayerControls.svelte
<script lang="ts">
    import { getImageUrl } from '$lib/utils/imageUtils';
    import PlayerHeader from './PlayerHeader.svelte';
    import ProgressControl from './ProgressControl.svelte';
    import Icon from '$lib/components/Icons/Icon.svelte';

    interface Props {
        currentTrack: MusicKit.MediaItem | undefined;
        isPlaying: boolean;
        switchPrev: () => void;
        switchNext: () => void;
        onPlayPause: () => void;
        isScrobblingEnabled: boolean;
        onScrobblingSwitch: (enabled: boolean) => void;
        lastfmAuthenticated: boolean;
    }

    let {
        currentTrack,
        isPlaying,
        switchPrev,
        switchNext,
        onPlayPause,
        isScrobblingEnabled,
        onScrobblingSwitch,
        lastfmAuthenticated
    }: Props = $props();

    let artworkUrl = $derived(
        currentTrack?.attributes?.artwork?.url
            ? getImageUrl(currentTrack.attributes.artwork.url)
            : 'default-album-cover.png'
    );
</script>

<div class="player-controls">
    <div class="art-container">
        {#if currentTrack}
            <PlayerHeader
                {currentTrack}
                {isScrobblingEnabled}
                {onScrobblingSwitch}
                {lastfmAuthenticated}
            />
        {/if}
        <div class="album-art" style:background-image="url({artworkUrl})">
            <div class="controls-container">
                <div class="progress-row">
                    <ProgressControl />
                </div>
                <button
                    class="control-button"
                    onclick={() => switchPrev()}
                    aria-label="previous"
                >
                    <Icon name="step-backward" size={24} />
                </button>
                <button
                    class="control-button"
                    onclick={() => onPlayPause()}
                    aria-label={isPlaying ? 'pause' : 'play'}
                >
                    <Icon name={isPlaying ? 'pause' : 'play'} size={24} />
                </button>
                <button
                    class="control-button"
                    onclick={() => switchNext()}
                    aria-label="next"
                >
                    <Icon name="step-forward" size={24} />
                </button>
            </div>
        </div>
    </div>
</div>

// LastApple.Web/ClientApp/src/components/Player/PlayerControls.tsx
import { ProgressControl } from "./ProgressControl";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faStepBackward } from "@fortawesome/free-solid-svg-icons/faStepBackward";
import { faPause, faPlay, faStepForward } from "@fortawesome/free-solid-svg-icons";
import React from 'react';
import { PlayerHeader, PlayerHeaderProps } from "./PlayerHeader";
import { getImageUrl } from "../../utils/imageUtils";

const containerStyles: React.CSSProperties = {
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis'
};

const controlsContainerStyles: React.CSSProperties = {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    background: '#00000099',
    padding: '10px',
    lineHeight: 1
};

const albumArtStyles: React.CSSProperties = {
    textAlign: 'center',
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    display: 'inline-block',
    width: '100%',
    maxWidth: '400px',
    height: '400px'
};

const artContainerStyles: React.CSSProperties = {
    textAlign: 'center',
    position: 'relative',
    padding: '10px',
    borderBottom: '1px solid #222'
};

const buttonStyles: React.CSSProperties = {
    background: 'none',
    border: 'none',
    fontSize: '35px',
    outline: 'none',
    margin: '0 25px',
    cursor: 'pointer'
};

type PlayerControlsProps = { currentTrack: MusicKit.MediaItem, isPlaying: boolean, switchPrev(): void, switchNext(): void, onPlayPause(): void } & PlayerHeaderProps;

export const PlayerControls = (props: PlayerControlsProps) =>
    <div className="player-controls" style={containerStyles}>
        <div style={artContainerStyles}>
            {props.currentTrack && <PlayerHeader
                currentTrack={props.currentTrack}
                isScrobblingEnabled={props.isScrobblingEnabled}
                onScrobblingSwitch={props.onScrobblingSwitch}
                lastfmAuthenticated={props.lastfmAuthenticated}
            />}
            <div className={'album-art'} style={{
                backgroundImage: `url(${getImageUrl(props.currentTrack?.attributes?.artwork?.url)})`,
                ...albumArtStyles
            }}>
                <div style={controlsContainerStyles}>
                    <div style={{ marginBottom: '2px' }}>
                        <ProgressControl />
                    </div>
                    <span style={buttonStyles} onClick={() => props.switchPrev()}>
                        <FontAwesomeIcon icon={faStepBackward}/>
                     </span>
                    <span style={buttonStyles} onClick={() => props.onPlayPause()}>
                        <FontAwesomeIcon icon={props.isPlaying ? faPause : faPlay} />
                    </span>
                    <span style={buttonStyles} onClick={() => props.switchNext()}>
                        <FontAwesomeIcon icon={faStepForward}/>
                    </span>
                </div>
            </div>
        </div>
    </div>;
