// LastApple.Web/ClientApp/src/components/Player/Playlist.tsx
import React, { memo, useCallback } from 'react';
import musicKit from '../../musicKit';
import { PlaylistTrack } from "./PlaylistTrack";
import { PlaylistTrackGroup } from "./PlaylistTrackGroup";

interface PlaylistProps {
    currentTrack: MusicKit.MediaItem;
    isPlaying: boolean;
    tracks: MusicKit.MediaItem[];
    offset: number;
    limit: number;
    showAlbumInfo: boolean;
    onRemove(position: number, count: number);
    onTrackSwitch(position: number): Promise<void>;
}

export const Playlist: React.FC<PlaylistProps> = memo(({ 
    currentTrack, 
    isPlaying, 
    tracks, 
    offset, 
    limit, 
    showAlbumInfo, 
    onRemove, 
    onTrackSwitch 
}) => {
    const getVisibleTracks = useCallback(() => {
        const firstTrackIndex = offset;
        const lastTrackIndex = firstTrackIndex + limit;

        return tracks.slice(firstTrackIndex, lastTrackIndex);
    }, [tracks, offset, limit]);

    const groupByAlbum = useCallback((tracksToGroup: MusicKit.MediaItem[]) => {
        return tracksToGroup.reduce((groups, next, index) => {
            if (groups.current === next.attributes.albumName) {
                groups.all[groups.all.length - 1].tracks.push(next);
            } else {
                groups.current = next.attributes.albumName;
                groups.all.push({ tracks: [next], index });
            }
            return groups;
        }, { all: [], current: '' });
    }, []);

    const removeItems = useCallback((position: number, count: number) => {
        // todo: implement remove from queue by entire queue reset
        //onRemove(position, count);
    }, []);

    const addAlbumToLibrary = useCallback(async (item: MusicKit.MediaItem) => {
        const albumId = item.relationships.albums.data[0].id;

        await musicKit.instance.api.music('/v1/me/library', { ids: { albums:[albumId] } }, { fetchOptions: { method: 'POST' } });
    }, []);

    const addToLibrary = useCallback(async (item: MusicKit.MediaItem) => {
        await musicKit.instance.api.music('/v1/me/library', { ids: { songs:[item.id] } }, { fetchOptions: { method: 'POST' } });
    }, []);

    if (!tracks.length)
        return null;

    const visibleTracks = getVisibleTracks();

    if (!showAlbumInfo)
        return <div className="playlist">
            {visibleTracks.map((track, index) => <PlaylistTrack
                key={index}
                track={track}
                isCurrent={currentTrack && track && currentTrack.id === track.id}
                isPlaying={currentTrack && track && isPlaying && currentTrack.id === track.id}
                index={index}
                groupOffset={0}
                onTrackSwitch={onTrackSwitch}
                addToLibrary={addToLibrary}
                addAlbumToLibrary={addAlbumToLibrary}
                onRemove={removeItems}
            />)}
        </div>;

    const grouped = groupByAlbum(visibleTracks);

    return <div className="playlist">
        {grouped.all.map(group =>
            <PlaylistTrackGroup
                key={group.index}
                tracks={group.tracks}
                currentTrack={currentTrack}
                isPlaying={isPlaying && group.tracks.some(t => t === currentTrack)}
                index={group.index}
                addAlbumToLibrary={addAlbumToLibrary}
                onRemove={removeItems}
            >
                { group.tracks.map((item, index) =>
                    <PlaylistTrack
                        key={index}
                        track={item}
                        isPlaying={isPlaying && item.id === currentTrack.id}
                        isCurrent={currentTrack && item.id === currentTrack.id}
                        index={index}
                        groupOffset={group.index}
                        onTrackSwitch={onTrackSwitch}
                        addToLibrary={addToLibrary}
                        addAlbumToLibrary={addAlbumToLibrary}
                        onRemove={onRemove}
                    />) }
            </PlaylistTrackGroup>)}
    </div>;
});

// LastApple.Web/ClientApp/src/lib/components/Player/Playlist.svelte
<script lang="ts">
    import musicKit from '$lib/services/musicKit.ts';
    import PlaylistTrack from './PlaylistTrack.svelte';
    import PlaylistTrackGroup from './PlaylistTrackGroup.svelte';

    interface Props {
        tracks: MusicKit.MediaItem[];
        currentTrack: MusicKit.MediaItem | undefined;
        isPlaying: boolean;
        offset: number;
        limit: number;
        showAlbumInfo: boolean;
        onRemove: (position: number, count: number) => void;
        onTrackSwitch: (index: number) => void;
    }

    let { tracks, currentTrack, isPlaying, offset, limit, showAlbumInfo, onRemove, onTrackSwitch }: Props = $props();

    interface TrackGroup {
        tracks: MusicKit.MediaItem[];
        index: number;
    }

    let visibleTracks = $derived(tracks.slice(offset, offset + limit));

    let groupedTracks = $derived.by(() => {
        const groups: { all: TrackGroup[]; current: string } = { all: [], current: '' };

        visibleTracks.forEach((track, index) => {
            if (groups.current === track.attributes.albumName) {
                groups.all[groups.all.length - 1].tracks.push(track);
            } else {
                groups.current = track.attributes.albumName;
                groups.all.push({ tracks: [track], index });
            }
        });

        return groups.all;
    });

    function removeItems(position: number, count: number) {
        // todo: implement remove from queue by entire queue reset
        // onRemove(position, count);
    }

    async function addAlbumToLibrary(item: MusicKit.MediaItem) {
        const instance = await musicKit.getInstance();
        const albumId = item.relationships?.albums?.data?.[0]?.id;
        if (albumId) {
            await instance.api.music('/v1/me/library', { ids: { albums: [albumId] } }, { fetchOptions: { method: 'POST' } });
        }
    }

    async function addToLibrary(item: MusicKit.MediaItem) {
        const instance = await musicKit.getInstance();
        await instance.api.music('/v1/me/library', { ids: { songs: [item.id] } }, { fetchOptions: { method: 'POST' } });
    }
</script>

{#if tracks.length > 0}
    <div class="playlist">
        {#if !showAlbumInfo}
            {#each visibleTracks as track, index (track.id)}
                <PlaylistTrack
                    {track}
                    isCurrent={currentTrack?.id === track.id}
                    isPlaying={isPlaying && currentTrack?.id === track.id}
                    {index}
                    groupOffset={0}
                    {onTrackSwitch}
                    {addToLibrary}
                    {addAlbumToLibrary}
                    onRemove={removeItems}
                />
            {/each}
        {:else}
            {#each groupedTracks as group (group.index)}
                <PlaylistTrackGroup
                    tracks={group.tracks}
                    {currentTrack}
                    isPlaying={isPlaying && group.tracks.some(t => t.id === currentTrack?.id)}
                    index={group.index}
                    {addAlbumToLibrary}
                    onRemove={removeItems}
                >
                    {#each group.tracks as item, trackIndex (item.id)}
                        <PlaylistTrack
                            track={item}
                            isPlaying={isPlaying && item.id === currentTrack?.id}
                            isCurrent={currentTrack?.id === item.id}
                            index={trackIndex}
                            groupOffset={group.index}
                            {onTrackSwitch}
                            {addToLibrary}
                            {addAlbumToLibrary}
                            onRemove={onRemove}
                        />
                    {/each}
                </PlaylistTrackGroup>
            {/each}
        {/if}
    </div>
{/if}
