// LastApple.Web/ClientApp/src/components/Footer.tsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import appStoreBadge from '../images/app-store-badge.svg';
import React from 'react';

export const Footer = () => <div style={{ display: 'flex', justifyContent: 'center', padding: '10px 20px', borderTop: '1px solid #404040' }}>
    <a href={'https://apps.apple.com/app/lastream/id1483386771'}>
        <img src={appStoreBadge} alt={'App Store Badge'} />
    </a>
    <div style={{ display: 'flex', alignItems: 'center', width: '120px', padding: '2px 5px', marginLeft: '25px', border: '1px solid #A6A6A6', borderRadius: '5px', background: '#000' }}>
        <a style={{ color: '#FFF', display: 'flex', alignItems: 'center', width: '100%', textDecoration: 'none' }}
            href='https://twitter.com/vitaliykapral'
            target="_blank" rel="noopener noreferrer">
            <FontAwesomeIcon icon={["fab", 'twitter']} style={{ fontSize: '1.5rem', marginRight: '5px', marginLeft: '5px', color: '#1ea1f2' }} />
            <div style={{ display: 'flex', flexDirection: 'column', lineHeight: '1.2', alignItems: 'center', flex: 1, fontFamily: 'Open Sans', marginTop: '3px' }}>
                <span style={{ fontSize: '9px' }}>Reach me on</span>
                <span style={{ fontSize: '16px' }}>Twitter</span>
            </div>
        </a>
    </div>
</div>;

// LastApple.Web/ClientApp/src/lib/components/Footer.svelte
<script lang="ts">
	// Footer component - migrated from React
</script>

<div style="display: flex; justify-content: center; padding: 10px 20px; border-top: 1px solid #404040;">
	<a href="https://apps.apple.com/app/lastream/id1483386771">
		<img src="/app-store-badge.svg" alt="App Store Badge" />
	</a>
	<div style="display: flex; align-items: center; width: 120px; padding: 2px 5px; margin-left: 25px; border: 1px solid #A6A6A6; border-radius: 5px; background: #000;">
		<a 
			style="color: #FFF; display: flex; align-items: center; width: 100%; text-decoration: none;" 
			href="https://twitter.com/vitaliykapral" 
			target="_blank" 
			rel="noopener noreferrer"
		>
			<i class="fab fa-twitter" style="font-size: 1.5rem; margin-right: 5px; margin-left: 5px; color: #1ea1f2;"></i>
			<div style="display: flex; flex-direction: column; line-height: 1.2; align-items: center; flex: 1; font-family: 'Open Sans'; margin-top: 3px;">
				<span style="font-size: 9px;">Reach me on</span>
				<span style="font-size: 16px;">Twitter</span>
			</div>
		</a>
	</div>
</div>
