// LastApple.Web/ClientApp/src/components/NowPlaying.tsx
import React from "react";
import { StationPlayer } from "./Player/StationPlayer";
import {useAppContext} from '../AppContext';
import {useAppleUnauthenticatedWarning} from "../hooks/useAppleUnauthenticatedWarning";

interface INowPlayingProps {
    readonly showPlayer: boolean;
    readonly stationId: string;
}

export const NowPlaying: React.FunctionComponent<INowPlayingProps> = (props: INowPlayingProps) => {
    const appContext = useAppContext();
    const appleUnauthenticatedWarning = useAppleUnauthenticatedWarning();

    React.useEffect(
        () => {
            if (!!props.stationId && props.stationId !== appContext.latestStationId) {
                appContext.setLatestStationId(props.stationId);
            }
        },
        [appContext, props.stationId]
    );

    return (
        <div style={{ display: props.showPlayer ? 'block' : 'none' }}>
            {appleUnauthenticatedWarning.isShown && appleUnauthenticatedWarning.Element}
            <StationPlayer stationId={props.stationId} />
        </div>
    );
};

// LastApple.Web/ClientApp/src/lib/components/NowPlaying.svelte
<script lang="ts">
    import StationPlayer from './Player/StationPlayer.svelte';
    import AppleUnauthenticatedWarning from './AppleUnauthenticatedWarning.svelte';
    import { appleUnauthenticatedWarning } from '$lib/stores/appleUnauthenticatedWarning';
    import { latestStationId } from '$lib/stores/app';

    interface Props {
        showPlayer: boolean;
        stationId: string;
    }

    let { showPlayer, stationId }: Props = $props();

    // Update latest station ID when stationId changes
    $effect(() => {
        if (stationId && stationId !== $latestStationId) {
            latestStationId.set(stationId);
        }
    });
</script>

<div class="now-playing" style:display={showPlayer ? 'block' : 'none'}>
    {#if $appleUnauthenticatedWarning}
        <AppleUnauthenticatedWarning />
    {/if}
    <StationPlayer {stationId} />
</div>
