// LastApple.Web/ClientApp/src/components/StationsList.tsx
import React, { Component } from "react";
import { Tag } from "./Stations/Tag";
import { SingleArtist } from "./Stations/SingleArtist";
import { SimilarArtists } from "./Stations/SimilarArtists";
import { Redirect } from "react-router";
import { StationDescriptor } from "./StationDescriptor";
import { MyLibrary } from "./Stations/MyLibrary";

export class StationsList extends Component<{}, { triggerStationCreate: boolean, createdStationId: string }> {
    constructor(props) {
        super(props);

        this.state = { triggerStationCreate: false, createdStationId: null };
    }

    render(): React.ReactNode {
        if (this.state.createdStationId) {
            return <Redirect to={`/station/${this.state.createdStationId}`}/>
        }

        return <div className='station-list' style={{ padding: '5px', display: 'grid' }}>
                <StationDescriptor definition={MyLibrary.Definition} StationComponent={MyLibrary} />
                <StationDescriptor definition={SingleArtist.Definition} StationComponent={SingleArtist} />
                <StationDescriptor definition={SimilarArtists.Definition} StationComponent={SimilarArtists} />
                <StationDescriptor definition={Tag.Definition} StationComponent={Tag} />
            </div>;
    }
}

// LastApple.Web/ClientApp/src/lib/components/StationsList.svelte
<script lang="ts">
	import StationDescriptor from './StationDescriptor.svelte';
	import MyLibrary, { Definition as MyLibraryDef } from './Stations/MyLibrary.svelte';
	import SingleArtist, { Definition as SingleArtistDef } from './Stations/SingleArtist.svelte';
	import SimilarArtists, { Definition as SimilarArtistsDef } from './Stations/SimilarArtists.svelte';
	import Tag, { Definition as TagDef } from './Stations/Tag.svelte';
</script>

<div class="station-list" style="padding: 5px; display: grid;">
	<StationDescriptor definition={MyLibraryDef} StationComponent={MyLibrary} />
	<StationDescriptor definition={SingleArtistDef} StationComponent={SingleArtist} />
	<StationDescriptor definition={SimilarArtistsDef} StationComponent={SimilarArtists} />
	<StationDescriptor definition={TagDef} StationComponent={Tag} />
</div>
